import { InventoryItem, Branch, User, Activity, StockAdjustment, Alert } from './types'

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Bigas (Rice) - 25kg Bag',
    sku: 'BIG-001',
    quantity: 45,
    price: 1250.00,
    reorderLevel: 50,
    expiryDate: new Date(2027, 6, 15),
    supplier: 'NFA Trading Co.',
    branch: 'Manila Branch',
    status: 'low-stock',
    lastRestocked: new Date(2026, 3, 10),
  },
  {
    id: '2',
    name: 'Asukal (Sugar) - 10kg Bag',
    sku: 'ASU-002',
    quantity: 120,
    price: 580.00,
    reorderLevel: 30,
    expiryDate: new Date(2027, 8, 20),
    supplier: 'Central Azucarera',
    branch: 'Manila Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 4, 5),
  },
  {
    id: '3',
    name: 'Gatas (Milk) - 1L Carton',
    sku: 'GAT-003',
    quantity: 8,
    price: 95.00,
    reorderLevel: 20,
    expiryDate: new Date(2026, 5, 10),
    supplier: 'Alaska Milk Corp.',
    branch: 'Cebu Branch',
    status: 'expiring',
    lastRestocked: new Date(2026, 3, 20),
  },
  {
    id: '4',
    name: 'Mantika (Oil) - 2L Bottle',
    sku: 'MAN-004',
    quantity: 65,
    price: 320.00,
    reorderLevel: 25,
    expiryDate: new Date(2028, 5, 1),
    supplier: 'Bohol Oil Mills',
    branch: 'Manila Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 2, 15),
  },
  {
    id: '5',
    name: 'Asin (Salt) - 1kg Pack',
    sku: 'ASN-005',
    quantity: 2,
    price: 45.00,
    reorderLevel: 15,
    expiryDate: new Date(2027, 7, 30),
    supplier: 'Pangasinan Salt Traders',
    branch: 'Davao Branch',
    status: 'low-stock',
    lastRestocked: new Date(2026, 1, 1),
  },
  {
    id: '6',
    name: 'Keso (Cheese) - 500g Block',
    sku: 'KES-006',
    quantity: 35,
    price: 280.00,
    reorderLevel: 20,
    expiryDate: new Date(2026, 6, 5),
    supplier: 'Magnolia Dairy',
    branch: 'Cebu Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 4, 10),
  },
  {
    id: '7',
    name: 'Itlog (Eggs) - 30-count Tray',
    sku: 'ITL-007',
    quantity: 18,
    price: 250.00,
    reorderLevel: 10,
    expiryDate: new Date(2026, 5, 28),
    supplier: 'San Miguel Poultry',
    branch: 'Manila Branch',
    status: 'expiring',
    lastRestocked: new Date(2026, 4, 15),
  },
  {
    id: '8',
    name: 'Tinapay (Bread) - White Loaf',
    sku: 'TIN-008',
    quantity: 250,
    price: 75.00,
    reorderLevel: 100,
    expiryDate: new Date(2026, 5, 25),
    supplier: 'Gardenia Philippines',
    branch: 'Davao Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 4, 20),
  },
  {
    id: '9',
    name: 'Toyo (Soy Sauce) - 1L Bottle',
    sku: 'TOY-009',
    quantity: 90,
    price: 85.00,
    reorderLevel: 30,
    expiryDate: new Date(2027, 11, 15),
    supplier: 'Datu Puti Corp.',
    branch: 'Cebu Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 3, 1),
  },
  {
    id: '10',
    name: 'Suka (Vinegar) - 1L Bottle',
    sku: 'SUK-010',
    quantity: 75,
    price: 65.00,
    reorderLevel: 25,
    expiryDate: new Date(2027, 9, 10),
    supplier: 'Datu Puti Corp.',
    branch: 'Davao Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 2, 20),
  },
  {
    id: '11',
    name: 'Sardinas (Sardines) - 155g Can',
    sku: 'SAR-011',
    quantity: 5,
    price: 32.00,
    reorderLevel: 40,
    expiryDate: new Date(2027, 3, 18),
    supplier: 'Mega Sardines Inc.',
    branch: 'Manila Branch',
    status: 'low-stock',
    lastRestocked: new Date(2026, 1, 10),
  },
  {
    id: '12',
    name: 'Noodles (Pancit Canton) - 60g Pack',
    sku: 'NOD-012',
    quantity: 200,
    price: 14.00,
    reorderLevel: 80,
    expiryDate: new Date(2027, 5, 22),
    supplier: 'Lucky Me! / Monde Nissin',
    branch: 'Cebu Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 4, 3),
  },
  {
    id: '13',
    name: 'Kape (Coffee) - 250g Pack',
    sku: 'KAP-013',
    quantity: 40,
    price: 195.00,
    reorderLevel: 15,
    expiryDate: new Date(2027, 8, 30),
    supplier: 'Benguet Coffee Traders',
    branch: 'Davao Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 3, 25),
  },
  {
    id: '14',
    name: 'Gata (Coconut Milk) - 400ml Can',
    sku: 'GTA-014',
    quantity: 55,
    price: 48.00,
    reorderLevel: 20,
    expiryDate: new Date(2027, 7, 14),
    supplier: 'Fiesta Coconut Products',
    branch: 'Manila Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 4, 8),
  },
  {
    id: '15',
    name: 'Patis (Fish Sauce) - 750ml Bottle',
    sku: 'PAT-015',
    quantity: 60,
    price: 72.00,
    reorderLevel: 25,
    expiryDate: new Date(2027, 10, 5),
    supplier: 'Rufina Patis Factory',
    branch: 'Cebu Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 2, 12),
  },
  {
    id: '16',
    name: 'Bagoong (Shrimp Paste) - 250g Jar',
    sku: 'BAG-016',
    quantity: 30,
    price: 110.00,
    reorderLevel: 10,
    expiryDate: new Date(2027, 4, 20),
    supplier: 'Barrio Fiesta Foods',
    branch: 'Davao Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 3, 15),
  },
  {
    id: '17',
    name: 'Corned Beef - 260g Can',
    sku: 'CRN-017',
    quantity: 3,
    price: 120.00,
    reorderLevel: 30,
    expiryDate: new Date(2026, 5, 15),
    supplier: 'CDO Foodsphere',
    branch: 'Cebu Branch',
    status: 'low-stock',
    lastRestocked: new Date(2026, 0, 20),
  },
  {
    id: '18',
    name: 'Calamansi Juice - 1L Bottle',
    sku: 'CAL-018',
    quantity: 45,
    price: 55.00,
    reorderLevel: 20,
    expiryDate: new Date(2026, 6, 10),
    supplier: 'Del Monte Philippines',
    branch: 'Davao Branch',
    status: 'normal',
    lastRestocked: new Date(2026, 4, 1),
  },
]

export const mockBranches: Branch[] = [
  {
    id: '1',
    name: 'Manila Branch',
    address: 'BGC, Taguig City',
    city: 'Metro Manila',
    manager: 'Maria Santos',
    contact: '0917-123-4567',
    email: 'maria.santos@invsys.ph',
    status: 'active',
  },
  {
    id: '2',
    name: 'Cebu Branch',
    address: 'IT Park, Lahug',
    city: 'Cebu City',
    manager: 'Juan Dela Cruz',
    contact: '0918-234-5678',
    email: 'juan.delacruz@invsys.ph',
    status: 'active',
  },
  {
    id: '3',
    name: 'Davao Branch',
    address: 'JP Laurel Avenue',
    city: 'Davao City',
    manager: 'Rosa Garcia',
    contact: '0919-345-6789',
    email: 'rosa.garcia@invsys.ph',
    status: 'active',
  },
]

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Administrator',
    email: 'admin@invsys.ph',
    role: 'admin',
    assignedBranch: 'All Branches',
    status: 'active',
    lastLogin: new Date(2026, 4, 5, 14, 30),
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria.santos@invsys.ph',
    role: 'branch-manager',
    assignedBranch: 'Manila Branch',
    status: 'active',
    lastLogin: new Date(2026, 4, 5, 10, 15),
  },
  {
    id: '3',
    name: 'Juan Dela Cruz',
    email: 'juan.delacruz@invsys.ph',
    role: 'branch-manager',
    assignedBranch: 'Cebu Branch',
    status: 'active',
    lastLogin: new Date(2026, 4, 4, 16, 45),
  },
  {
    id: '4',
    name: 'Rosa Garcia',
    email: 'rosa.garcia@invsys.ph',
    role: 'branch-manager',
    assignedBranch: 'Davao Branch',
    status: 'active',
    lastLogin: new Date(2026, 4, 5, 9, 0),
  },
  {
    id: '5',
    name: 'Anna Lopez',
    email: 'anna.lopez@invsys.ph',
    role: 'staff',
    assignedBranch: 'Manila Branch',
    status: 'active',
    lastLogin: new Date(2026, 4, 5, 9, 20),
  },
  {
    id: '6',
    name: 'Miguel Rodriguez',
    email: 'miguel.rodriguez@invsys.ph',
    role: 'staff',
    assignedBranch: 'Cebu Branch',
    status: 'active',
    lastLogin: new Date(2026, 4, 4, 15, 0),
  },
  {
    id: '7',
    name: 'Christine Reyes',
    email: 'christine.reyes@invsys.ph',
    role: 'staff',
    assignedBranch: 'Davao Branch',
    status: 'active',
    lastLogin: new Date(2026, 4, 5, 8, 30),
  },
]

export const mockActivities: Activity[] = [
  {
    id: '1',
    user: 'Maria Santos',
    action: 'Restocked',
    item: 'Asukal (Sugar) - 10kg Bag',
    branch: 'Manila Branch',
    timestamp: new Date(2026, 4, 5, 14, 20),
    details: 'Nagdagdag ng 50 units',
  },
  {
    id: '2',
    user: 'Juan Dela Cruz',
    action: 'Transferred',
    item: 'Gatas (Milk) - 1L Carton',
    branch: 'Cebu Branch',
    timestamp: new Date(2026, 4, 5, 13, 45),
    details: '20 units to Manila Branch',
  },
  {
    id: '3',
    user: 'Christine Reyes',
    action: 'Removed',
    item: 'Tinapay (Bread) - White Loaf',
    branch: 'Davao Branch',
    timestamp: new Date(2026, 4, 5, 12, 30),
    details: '5 units (expired)',
  },
  {
    id: '4',
    user: 'Administrator',
    action: 'Created',
    item: 'System Update',
    branch: 'System',
    timestamp: new Date(2026, 4, 4, 10, 0),
    details: 'Updated inventory settings',
  },
  {
    id: '5',
    user: 'Rosa Garcia',
    action: 'Restocked',
    item: 'Kape (Coffee) - 250g Pack',
    branch: 'Davao Branch',
    timestamp: new Date(2026, 4, 4, 16, 15),
    details: 'Nagdagdag ng 25 units',
  },
]

export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'low-stock',
    item: 'Bigas (Rice) - 25kg Bag',
    branch: 'Manila Branch',
    message: 'Stock level below reorder point',
    severity: 'warning',
    timestamp: new Date(2026, 4, 5, 13, 0),
    read: false,
  },
  {
    id: '2',
    type: 'expiring',
    item: 'Itlog (Eggs) - 30-count Tray',
    branch: 'Manila Branch',
    message: 'Product expires in 12 days',
    severity: 'warning',
    timestamp: new Date(2026, 4, 5, 11, 30),
    read: false,
  },
  {
    id: '3',
    type: 'low-stock',
    item: 'Asin (Salt) - 1kg Pack',
    branch: 'Davao Branch',
    message: 'Critical stock level',
    severity: 'critical',
    timestamp: new Date(2026, 4, 5, 10, 0),
    read: false,
  },
  {
    id: '4',
    type: 'expiring',
    item: 'Gatas (Milk) - 1L Carton',
    branch: 'Cebu Branch',
    message: 'Product expires in 3 days',
    severity: 'critical',
    timestamp: new Date(2026, 4, 4, 14, 20),
    read: true,
  },
  {
    id: '5',
    type: 'system',
    message: 'System backup completed successfully',
    severity: 'info',
    timestamp: new Date(2026, 4, 3, 2, 0),
    read: true,
  },
  {
    id: '6',
    type: 'low-stock',
    item: 'Corned Beef - 260g Can',
    branch: 'Cebu Branch',
    message: 'Stock level critically low',
    severity: 'critical',
    timestamp: new Date(2026, 4, 5, 9, 30),
    read: false,
  },
]

export const mockStockAdjustments: StockAdjustment[] = [
  {
    id: '1',
    itemId: '2',
    itemName: 'Asukal (Sugar) - 10kg Bag',
    type: 'add',
    quantity: 50,
    toBranch: 'Manila Branch',
    reason: 'Regular restock',
    user: 'Maria Santos',
    timestamp: new Date(2026, 4, 5, 14, 20),
  },
  {
    id: '2',
    itemId: '3',
    itemName: 'Gatas (Milk) - 1L Carton',
    type: 'transfer',
    quantity: 20,
    fromBranch: 'Cebu Branch',
    toBranch: 'Manila Branch',
    reason: 'Demand adjustment',
    user: 'Juan Dela Cruz',
    timestamp: new Date(2026, 4, 5, 13, 45),
  },
  {
    id: '3',
    itemId: '8',
    itemName: 'Tinapay (Bread) - White Loaf',
    type: 'remove',
    quantity: 5,
    fromBranch: 'Davao Branch',
    reason: 'Expired items',
    user: 'Christine Reyes',
    timestamp: new Date(2026, 4, 5, 12, 30),
  },
]
