import { InventoryItem, Branch, User, Activity, StockAdjustment, Alert } from './types'

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Organic Whole Wheat Flour',
    sku: 'OWF-001',
    quantity: 45,
    reorderLevel: 50,
    expiryDate: new Date(2025, 6, 15),
    supplier: 'Green Mill Co.',
    branch: 'Main Branch',
    status: 'low-stock',
    lastRestocked: new Date(2026, 0, 10),
  },
  {
    id: '2',
    name: 'Premium Olive Oil',
    sku: 'POL-002',
    quantity: 120,
    reorderLevel: 30,
    expiryDate: new Date(2027, 2, 20),
    supplier: 'Mediterranean Imports',
    branch: 'Downtown Store',
    status: 'normal',
    lastRestocked: new Date(2026, 1, 5),
  },
  {
    id: '3',
    name: 'Almond Milk 1L',
    sku: 'AM-003',
    quantity: 8,
    reorderLevel: 20,
    expiryDate: new Date(2026, 3, 10),
    supplier: 'Dairy Alternatives Inc.',
    branch: 'Uptown Store',
    status: 'expiring',
    lastRestocked: new Date(2026, 0, 20),
  },
  {
    id: '4',
    name: 'Organic Honey 500g',
    sku: 'OH-004',
    quantity: 65,
    reorderLevel: 25,
    expiryDate: new Date(2028, 5, 1),
    supplier: 'Bee Happy Farm',
    branch: 'Main Branch',
    status: 'normal',
    lastRestocked: new Date(2025, 11, 15),
  },
  {
    id: '5',
    name: 'Quinoa Pack 1kg',
    sku: 'QP-005',
    quantity: 2,
    reorderLevel: 15,
    expiryDate: new Date(2026, 7, 30),
    supplier: 'Health Grains Ltd.',
    branch: 'East End Store',
    status: 'low-stock',
    lastRestocked: new Date(2025, 10, 1),
  },
  {
    id: '6',
    name: 'Cheddar Cheese Block 500g',
    sku: 'CCB-006',
    quantity: 35,
    reorderLevel: 20,
    expiryDate: new Date(2026, 4, 5),
    supplier: 'Dairy Delights',
    branch: 'Downtown Store',
    status: 'normal',
    lastRestocked: new Date(2026, 1, 10),
  },
  {
    id: '7',
    name: 'Wild Salmon Fillet 1kg',
    sku: 'WSF-007',
    quantity: 18,
    reorderLevel: 10,
    expiryDate: new Date(2026, 2, 28),
    supplier: 'Ocean Fresh Co.',
    branch: 'Main Branch',
    status: 'expiring',
    lastRestocked: new Date(2026, 1, 15),
  },
  {
    id: '8',
    name: 'Free-Range Eggs (Dozen)',
    sku: 'FRE-008',
    quantity: 250,
    reorderLevel: 100,
    expiryDate: new Date(2026, 2, 25),
    supplier: 'Happy Hens Farm',
    branch: 'Uptown Store',
    status: 'normal',
    lastRestocked: new Date(2026, 1, 20),
  },
]

export const mockBranches: Branch[] = [
  {
    id: '1',
    name: 'Main Branch',
    address: '123 Main Street',
    city: 'New York',
    manager: 'Sarah Johnson',
    contact: '555-0101',
    email: 'sarah.johnson@company.com',
    status: 'active',
  },
  {
    id: '2',
    name: 'Downtown Store',
    address: '456 Park Avenue',
    city: 'New York',
    manager: 'Michael Chen',
    contact: '555-0102',
    email: 'michael.chen@company.com',
    status: 'active',
  },
  {
    id: '3',
    name: 'Uptown Store',
    address: '789 Fifth Avenue',
    city: 'New York',
    manager: 'Emily Rodriguez',
    contact: '555-0103',
    email: 'emily.rodriguez@company.com',
    status: 'active',
  },
  {
    id: '4',
    name: 'East End Store',
    address: '321 East Street',
    city: 'New York',
    manager: 'David Kim',
    contact: '555-0104',
    email: 'david.kim@company.com',
    status: 'inactive',
  },
]

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@company.com',
    role: 'admin',
    assignedBranch: 'Main Branch',
    status: 'active',
    lastLogin: new Date(2026, 2, 16, 14, 30),
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'branch-manager',
    assignedBranch: 'Main Branch',
    status: 'active',
    lastLogin: new Date(2026, 2, 16, 10, 15),
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    role: 'branch-manager',
    assignedBranch: 'Downtown Store',
    status: 'active',
    lastLogin: new Date(2026, 2, 15, 16, 45),
  },
  {
    id: '4',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@company.com',
    role: 'staff',
    assignedBranch: 'Uptown Store',
    status: 'active',
    lastLogin: new Date(2026, 2, 16, 9, 20),
  },
  {
    id: '5',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    role: 'staff',
    assignedBranch: 'Main Branch',
    status: 'inactive',
    lastLogin: new Date(2026, 1, 20, 15, 0),
  },
]

export const mockActivities: Activity[] = [
  {
    id: '1',
    user: 'Sarah Johnson',
    action: 'Restocked',
    item: 'Premium Olive Oil',
    branch: 'Downtown Store',
    timestamp: new Date(2026, 2, 16, 14, 20),
    details: 'Added 50 units',
  },
  {
    id: '2',
    user: 'Michael Chen',
    action: 'Transferred',
    item: 'Organic Honey 500g',
    branch: 'Downtown Store',
    timestamp: new Date(2026, 2, 16, 13, 45),
    details: '20 units to Main Branch',
  },
  {
    id: '3',
    user: 'Lisa Anderson',
    action: 'Removed',
    item: 'Almond Milk 1L',
    branch: 'Uptown Store',
    timestamp: new Date(2026, 2, 16, 12, 30),
    details: '5 units (expired)',
  },
  {
    id: '4',
    user: 'John Doe',
    action: 'Created',
    item: 'New Branch Added',
    branch: 'System',
    timestamp: new Date(2026, 2, 15, 10, 0),
    details: 'East End Store',
  },
  {
    id: '5',
    user: 'Sarah Johnson',
    action: 'Updated',
    item: 'Inventory Settings',
    branch: 'Main Branch',
    timestamp: new Date(2026, 2, 14, 16, 15),
    details: 'Changed reorder level',
  },
]

export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'low-stock',
    item: 'Organic Whole Wheat Flour',
    branch: 'Main Branch',
    message: 'Stock level below reorder point',
    severity: 'warning',
    timestamp: new Date(2026, 2, 16, 13, 0),
    read: false,
  },
  {
    id: '2',
    type: 'expiring',
    item: 'Wild Salmon Fillet 1kg',
    branch: 'Main Branch',
    message: 'Product expires in 12 days',
    severity: 'warning',
    timestamp: new Date(2026, 2, 16, 11, 30),
    read: false,
  },
  {
    id: '3',
    type: 'low-stock',
    item: 'Quinoa Pack 1kg',
    branch: 'East End Store',
    message: 'Critical stock level',
    severity: 'critical',
    timestamp: new Date(2026, 2, 16, 10, 0),
    read: false,
  },
  {
    id: '4',
    type: 'expiring',
    item: 'Almond Milk 1L',
    branch: 'Uptown Store',
    message: 'Product expires in 3 days',
    severity: 'critical',
    timestamp: new Date(2026, 2, 15, 14, 20),
    read: true,
  },
  {
    id: '5',
    type: 'system',
    message: 'System backup completed successfully',
    severity: 'info',
    timestamp: new Date(2026, 2, 14, 2, 0),
    read: true,
  },
]

export const mockStockAdjustments: StockAdjustment[] = [
  {
    id: '1',
    itemId: '2',
    itemName: 'Premium Olive Oil',
    type: 'add',
    quantity: 50,
    toBranch: 'Downtown Store',
    reason: 'Regular restock',
    user: 'Sarah Johnson',
    timestamp: new Date(2026, 2, 16, 14, 20),
  },
  {
    id: '2',
    itemId: '4',
    itemName: 'Organic Honey 500g',
    type: 'transfer',
    quantity: 20,
    fromBranch: 'Downtown Store',
    toBranch: 'Main Branch',
    reason: 'Demand adjustment',
    user: 'Michael Chen',
    timestamp: new Date(2026, 2, 16, 13, 45),
  },
  {
    id: '3',
    itemId: '3',
    itemName: 'Almond Milk 1L',
    type: 'remove',
    quantity: 5,
    fromBranch: 'Uptown Store',
    reason: 'Expired items',
    user: 'Lisa Anderson',
    timestamp: new Date(2026, 2, 16, 12, 30),
  },
]
